<?php

namespace ContainerNEEjSn7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecipeControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Api\V1\RecipeController' shared autowired service.
     *
     * @return \App\Controller\Api\V1\RecipeController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Api/V1/RecipeController.php';

        $container->services['App\\Controller\\Api\\V1\\RecipeController'] = $instance = new \App\Controller\Api\V1\RecipeController();

        $instance->setContainer(($container->privates['.service_locator.5nX7ca3'] ?? $container->load('get_ServiceLocator_5nX7ca3Service'))->withContext('App\\Controller\\Api\\V1\\RecipeController', $container));

        return $instance;
    }
}
