<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHyLrRBl\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHyLrRBl/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHyLrRBl.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHyLrRBl\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHyLrRBl\App_KernelDevDebugContainer([
    'container.build_hash' => 'HyLrRBl',
    'container.build_id' => '4fe6ea03',
    'container.build_time' => 1607005925,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHyLrRBl');
